server:
  port: 8082
  servlet:
    contextPath: /
spring:
  datasource:
    password: juHijero0609..
    url: jdbc:mysql://localhost:3306/childdb?user=root
    driverClassName: com.mysql.cj.jdbc.Driver